cesga/2020 unloaded
        Preparing the environment for use of the CESGA 2020 software stack.
        Please rebuild modules cache: module --ignore-cache avail
     
cesga/2020 loaded
python/3.9.9 loaded
jupyter-server/1.13.5-python-3.9.9 loaded
jupyterlab/3.2.4-python-3.9.9 loaded
  0%|          | 0/480 [00:00<?, ?batch/s]Train Epoch 0:   0%|          | 0/480 [00:14<?, ?batch/s]Train Epoch 0:   0%|          | 0/480 [00:20<?, ?batch/s]
Traceback (most recent call last):
  File "/mnt/netapp2/Store_uni/home/usc/ec/rsm/fivesegmentor/code/training/run_benchmark.py", line 508, in <module>
    train_and_evaluate(model_name, dataset, logging_enabled=args.logging)
  File "/mnt/netapp2/Store_uni/home/usc/ec/rsm/fivesegmentor/code/training/run_benchmark.py", line 254, in train_and_evaluate
    result_train = traverseDataset(
  File "/mnt/netapp2/Store_uni/home/usc/ec/rsm/fivesegmentor/code/utils/utils.py", line 140, in traverseDataset
    out = model(data)
  File "/mnt/netapp2/Home_FT2/home/usc/ec/rsm/vroi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/netapp2/Store_uni/home/usc/ec/rsm/fivesegmentor/code/models/roinet.py", line 132, in forward
    out3 = self.dict_module["merge3"](out3)            # (B, 64, H/2, W/2)
  File "/mnt/netapp2/Home_FT2/home/usc/ec/rsm/vroi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/netapp2/Home_FT2/home/usc/ec/rsm/vroi/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/mnt/netapp2/Home_FT2/home/usc/ec/rsm/vroi/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/netapp2/Home_FT2/home/usc/ec/rsm/vroi/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/mnt/netapp2/Home_FT2/home/usc/ec/rsm/vroi/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [96, 192, 3, 3], expected input[1, 288, 1024, 1024] to have 192 channels, but got 288 channels instead
